# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
	adapter: mysql2
	encoding: utf8
	pool: 5
	username: root
	password:
	socket: /tmp/mysql.sock

development:
	<<: *default
	database: cookbook-app_development

test:
	<<: *default
	database: cookbook-app_test

#
production:
	database: cookbook-app_production
	adapter: postgrespl
		encoding:unicode
		pool:5
